addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.14")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"    % "0.5.1")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"   % "3.9.4")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"        % "2.0.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.9.21")
addSbtPlugin("com.47deg"                 % "sbt-microsites" % "1.2.1")
