addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.3.3")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"    % "0.6.3")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"   % "3.9.13")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"        % "2.1.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.6")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.10.1")
addSbtPlugin("com.47deg"                 % "sbt-microsites" % "1.3.4")
